import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { EvaluationCriterion } from './criteria';

export interface TeacherPerformanceData {
  id: string;
  name: string;
  email?: string;
  department: string;
  evaluationCount: number;
  averageScore: number;
  criteriaScores: Record<string, number>;
}

export interface DepartmentStatData {
  name: string;
  average: number;
  teacherCount?: number;
  evaluationCount?: number;
}

export interface CriteriaStatData {
  name: string;
  average: number;
}

export interface ExportReportOptions {
  institutionName?: string;
  campusLocation?: string;
  academicYear?: string;
  semester?: string;
  selectedDepartment?: string;
  generatedBy?: string;
  reports: TeacherPerformanceData[];
  criteriaList: EvaluationCriterion[];
  departmentStats: DepartmentStatData[];
  criteriaStats: CriteriaStatData[];
}

/**
 * Returns descriptive qualitative rating band based on score / 5.00
 */
export function getPerformanceDescriptor(score: number): { label: string; code: string; color: string } {
  if (score >= 4.50) return { label: 'Outstanding', code: 'O', color: '#10b981' };
  if (score >= 3.50) return { label: 'Very Satisfactory', code: 'VS', color: '#3b82f6' };
  if (score >= 2.50) return { label: 'Satisfactory', code: 'S', color: '#eab308' };
  if (score >= 1.50) return { label: 'Fair / Needs Improvement', code: 'F', color: '#f97316' };
  if (score > 0) return { label: 'Unsatisfactory', code: 'US', color: '#ef4444' };
  return { label: 'No Evaluations Yet', code: 'N/A', color: '#9ca3af' };
}

/**
 * Generates and downloads a complete Administrative Summary CSV file
 */
export function exportPerformanceSummaryCSV(options: ExportReportOptions): void {
  const {
    institutionName = 'St. Alexius College',
    campusLocation = 'City of Koronadal, South Cotabato, Philippines',
    academicYear = '2025-2026',
    semester = '1st Semester',
    selectedDepartment = 'all',
    generatedBy = 'Administrator',
    reports,
    criteriaList,
    departmentStats
  } = options;

  const timestamp = new Date().toLocaleString();
  const filteredReports = selectedDepartment === 'all' 
    ? reports 
    : reports.filter(r => r.department === selectedDepartment);

  const totalEvaluations = filteredReports.reduce((sum, r) => sum + (r.evaluationCount || 0), 0);
  const ratedFaculty = filteredReports.filter(r => r.evaluationCount > 0);
  const overallAvg = ratedFaculty.length > 0 
    ? (ratedFaculty.reduce((sum, r) => sum + r.averageScore, 0) / ratedFaculty.length).toFixed(2)
    : '0.00';

  const rows: string[][] = [];

  // Metadata Block
  rows.push([`"${institutionName}"`]);
  rows.push([`"${campusLocation}"`]);
  rows.push(['TEACHER PERFORMANCE EVALUATION SYSTEM (TPES)']);
  rows.push(['OFFICIAL ADMINISTRATIVE PERFORMANCE SUMMARY REPORT']);
  rows.push([]);
  rows.push(['Academic Period', `"${academicYear} - ${semester}"`]);
  rows.push(['Scope / Filter', `"${selectedDepartment === 'all' ? 'All Departments / Institutional' : selectedDepartment}"`]);
  rows.push(['Generated By', `"${generatedBy}"`]);
  rows.push(['Export Timestamp', `"${timestamp}"`]);
  rows.push([]);

  // Executive Summary Statistics
  rows.push(['--- EXECUTIVE SUMMARY METRICS ---']);
  rows.push(['Metric', 'Value']);
  rows.push(['Total Faculty Roster', `${filteredReports.length}`]);
  rows.push(['Faculty with Completed Evaluations', `${ratedFaculty.length}`]);
  rows.push(['Total Student Evaluations Submitted', `${totalEvaluations}`]);
  rows.push(['Overall Institutional Mean Rating', `${overallAvg} / 5.00`]);
  rows.push(['Overall Qualitative Interpretation', `"${getPerformanceDescriptor(Number(overallAvg)).label}"`]);
  rows.push([]);

  // Departmental Summary if All
  if (departmentStats.length > 0 && selectedDepartment === 'all') {
    rows.push(['--- DEPARTMENTAL COMPARATIVE PERFORMANCE ---']);
    rows.push(['Department', 'Average Rating (/5.00)', 'Qualitative Descriptor']);
    departmentStats.forEach(d => {
      rows.push([
        `"${d.name}"`,
        `${d.average.toFixed(2)}`,
        `"${getPerformanceDescriptor(d.average).label}"`
      ]);
    });
    rows.push([]);
  }

  // Detailed Faculty Performance Table
  rows.push(['--- DETAILED FACULTY EVALUATION ROSTER ---']);
  
  // Build Dynamic Column Headers
  const headerCols = [
    'Rank',
    'Faculty Name',
    'Email Address',
    'Department / College',
    'Evaluations Received',
    ...criteriaList.map(c => `"${c.label} (/5.00)"`),
    'Overall Average (/5.00)',
    'Performance Band',
    'Rating Code'
  ];
  rows.push(headerCols);

  // Data rows
  filteredReports.forEach((teacher, idx) => {
    const descriptor = getPerformanceDescriptor(teacher.averageScore);
    const critValues = criteriaList.map(c => {
      const val = teacher.criteriaScores?.[c.id];
      return val !== undefined ? val.toFixed(2) : 'N/A';
    });

    const row = [
      `${idx + 1}`,
      `"${teacher.name}"`,
      `"${teacher.email || 'N/A'}"`,
      `"${teacher.department}"`,
      `${teacher.evaluationCount}`,
      ...critValues,
      `${teacher.averageScore > 0 ? teacher.averageScore.toFixed(2) : '0.00'}`,
      `"${descriptor.label}"`,
      `"${descriptor.code}"`
    ];
    rows.push(row);
  });

  rows.push([]);
  rows.push(['--- END OF ADMINISTRATIVE REPORT ---']);
  rows.push(['Note: This document is officially produced by the St. Alexius College TPES for faculty development, accreditation, and administrative record keeping.']);

  // Convert to CSV String
  const csvContent = rows.map(r => r.join(',')).join('\r\n');
  const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
  const filename = `SAC_TPES_Teacher_Performance_Summary_${selectedDepartment.replace(/[^a-zA-Z0-9]/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`;

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generates and downloads an Individual Faculty Performance Summary CSV
 */
export function exportIndividualTeacherCSV(
  teacher: TeacherPerformanceData,
  criteriaList: EvaluationCriterion[],
  metadata?: { academicYear?: string; semester?: string; generatedBy?: string }
): void {
  const timestamp = new Date().toLocaleString();
  const descriptor = getPerformanceDescriptor(teacher.averageScore);

  const rows: string[][] = [
    ['"St. Alexius College"'],
    ['"City of Koronadal, South Cotabato"'],
    ['"INDIVIDUAL FACULTY PERFORMANCE EVALUATION DOSSIER"'],
    [],
    ['Faculty Name', `"${teacher.name}"`],
    ['Email Address', `"${teacher.email || 'N/A'}"`],
    ['Department / College', `"${teacher.department}"`],
    ['Academic Period', `"${metadata?.academicYear || '2025-2026'} - ${metadata?.semester || '1st Semester'}"`],
    ['Evaluations Received', `${teacher.evaluationCount}`],
    ['Overall Performance Score', `${teacher.averageScore > 0 ? teacher.averageScore.toFixed(2) : '0.00'} / 5.00`],
    ['Performance Classification', `"${descriptor.label} (${descriptor.code})"`],
    ['Exported On', `"${timestamp}"`],
    ['Generated By', `"${metadata?.generatedBy || 'Administrator'}"`],
    [],
    ['--- CRITERIA PERFORMANCE BREAKDOWN ---'],
    ['Criteria ID', 'Evaluation Dimension', 'Score Obtained (/5.00)', 'Qualitative Descriptor']
  ];

  criteriaList.forEach(crit => {
    const score = teacher.criteriaScores?.[crit.id];
    const scoreText = score !== undefined ? score.toFixed(2) : 'N/A';
    const scoreDesc = score !== undefined ? getPerformanceDescriptor(score).label : 'No Data';
    rows.push([`"${crit.id}"`, `"${crit.label}"`, `${scoreText}`, `"${scoreDesc}"`]);
  });

  rows.push([]);
  rows.push(['--- ADMINISTRATIVE REMARKS & ENDORSEMENT ---']);
  rows.push(['Verified by Dean / Department Chair', '']);
  rows.push(['Acknowledged by Faculty Member', '']);

  const csvContent = rows.map(r => r.join(',')).join('\r\n');
  const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
  const filename = `SAC_Faculty_Summary_${teacher.name.replace(/[^a-zA-Z0-9]/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`;

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generates and downloads an Executive PDF Performance Summary Document
 */
export function exportPerformanceSummaryPDF(options: ExportReportOptions): void {
  const {
    institutionName = 'ST. ALEXIUS COLLEGE',
    campusLocation = 'City of Koronadal, South Cotabato, Philippines',
    academicYear = '2025-2026',
    semester = '1st Semester',
    selectedDepartment = 'all',
    generatedBy = 'Administrator',
    reports,
    criteriaList,
    departmentStats,
    criteriaStats
  } = options;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const filteredReports = selectedDepartment === 'all' 
    ? reports 
    : reports.filter(r => r.department === selectedDepartment);

  const totalEvaluations = filteredReports.reduce((sum, r) => sum + (r.evaluationCount || 0), 0);
  const ratedFaculty = filteredReports.filter(r => r.evaluationCount > 0);
  const overallAvg = ratedFaculty.length > 0 
    ? (ratedFaculty.reduce((sum, r) => sum + r.averageScore, 0) / ratedFaculty.length).toFixed(2)
    : '0.00';
  const overallDescriptor = getPerformanceDescriptor(Number(overallAvg));

  // --- PAGE HEADER DECORATION ---
  const renderHeader = (pageNum: number) => {
    // Top Banner Bar
    doc.setFillColor(30, 58, 138); // #1e3a8a Navy
    doc.rect(0, 0, pageWidth, 6, 'F');
    doc.setFillColor(212, 175, 55); // #d4af37 Gold Accent
    doc.rect(0, 6, pageWidth, 1.5, 'F');

    // Official Letterhead
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(30, 58, 138);
    doc.text(institutionName, pageWidth / 2, 16, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(campusLocation, pageWidth / 2, 20.5, { align: 'center' });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text('TEACHER PERFORMANCE EVALUATION SYSTEM (TPES)', pageWidth / 2, 26, { align: 'center' });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(212, 175, 55);
    doc.text('EXECUTIVE PERFORMANCE EVALUATION SUMMARY REPORT', pageWidth / 2, 30.5, { align: 'center' });

    // Thin separator line
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.5);
    doc.line(14, 33, pageWidth - 14, 33);
  };

  // Render first page header
  renderHeader(1);

  // --- REPORT METADATA GRID ---
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 35, pageWidth - 28, 18, 2, 2, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 35, pageWidth - 28, 18, 2, 2, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text('Academic Term:', 18, 40);
  doc.text('Target Scope:', 18, 45);
  doc.text('Date Generated:', 18, 50);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(15, 23, 42);
  doc.text(`${academicYear} • ${semester}`, 45, 40);
  doc.text(selectedDepartment === 'all' ? 'All Academic Departments (Institutional Roster)' : selectedDepartment, 45, 45);
  doc.text(new Date().toLocaleDateString('en-US', { dateStyle: 'medium', timeStyle: 'short' }), 45, 50);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text('Authorized By:', pageWidth / 2 + 10, 40);
  doc.text('Faculty Evaluated:', pageWidth / 2 + 10, 45);
  doc.text('Document Status:', pageWidth / 2 + 10, 50);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(15, 23, 42);
  doc.text(generatedBy, pageWidth / 2 + 38, 40);
  doc.text(`${ratedFaculty.length} of ${filteredReports.length} Faculty Members`, pageWidth / 2 + 38, 45);
  doc.setTextColor(16, 185, 129);
  doc.setFont('helvetica', 'bold');
  doc.text('Official Administrative Record', pageWidth / 2 + 38, 50);

  // --- EXECUTIVE KPI CARDS ---
  let startY = 57;
  const cardWidth = (pageWidth - 28 - 9) / 4;
  const cardHeight = 16;

  const kpis = [
    { label: 'Total Faculty', val: `${filteredReports.length}`, sub: 'Active Roster' },
    { label: 'Completed Evals', val: `${totalEvaluations}`, sub: 'Student Submissions' },
    { label: 'Institutional Mean', val: `${overallAvg}`, sub: 'Scale of 1.00 - 5.00' },
    { label: 'Rating Classification', val: `${overallDescriptor.code}`, sub: overallDescriptor.label }
  ];

  kpis.forEach((kpi, index) => {
    const cardX = 14 + (index * (cardWidth + 3));
    doc.setFillColor(index === 2 ? 239 : 248, index === 2 ? 246 : 250, index === 2 ? 255 : 252);
    doc.roundedRect(cardX, startY, cardWidth, cardHeight, 1.5, 1.5, 'F');
    doc.setDrawColor(index === 2 ? 191 : 226, index === 2 ? 219 : 232, index === 2 ? 254 : 240);
    doc.roundedRect(cardX, startY, cardWidth, cardHeight, 1.5, 1.5, 'S');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    doc.setTextColor(100, 116, 139);
    doc.text(kpi.label, cardX + cardWidth / 2, startY + 4, { align: 'center' });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(index === 2 ? 30 : 15, index === 2 ? 58 : 23, index === 2 ? 138 : 42);
    doc.text(kpi.val, cardX + cardWidth / 2, startY + 9.5, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(5.5);
    doc.setTextColor(100, 116, 139);
    doc.text(kpi.sub, cardX + cardWidth / 2, startY + 13.5, { align: 'center' });
  });

  // --- SUMMARY TABLES SECTION ---
  startY += 20;

  // Criteria Performance Summary Table
  const criteriaTableData = criteriaStats.map((c, i) => [
    `${i + 1}`,
    c.name,
    `${c.average.toFixed(2)} / 5.00`,
    getPerformanceDescriptor(c.average).label
  ]);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(30, 58, 138);
  doc.text('1. Institutional Criteria Performance Breakdown', 14, startY);

  autoTable(doc, {
    startY: startY + 2,
    head: [['#', 'Evaluation Dimension / Criteria', 'Mean Score', 'Performance Descriptor']],
    body: criteriaTableData,
    margin: { left: 14, right: 14 },
    theme: 'grid',
    headStyles: {
      fillColor: [30, 58, 138],
      textColor: [255, 255, 255],
      fontSize: 7.5,
      fontStyle: 'bold',
      halign: 'left'
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [30, 41, 59]
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 'auto' },
      2: { cellWidth: 28, halign: 'center', fontStyle: 'bold' },
      3: { cellWidth: 42, halign: 'center' }
    }
  });

  // Position for Faculty Roster Table
  const currentY = (doc as any).lastAutoTable ? (doc as any).lastAutoTable.finalY + 8 : startY + 40;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(30, 58, 138);
  doc.text('2. Faculty Individual Performance Roster & Rankings', 14, currentY);

  // Build Faculty Roster Table
  const facultyTableData = filteredReports.map((teacher, index) => {
    const desc = getPerformanceDescriptor(teacher.averageScore);
    return [
      `${index + 1}`,
      teacher.name,
      teacher.department,
      `${teacher.evaluationCount}`,
      teacher.averageScore > 0 ? `${teacher.averageScore.toFixed(2)}` : 'N/A',
      desc.label
    ];
  });

  autoTable(doc, {
    startY: currentY + 2,
    head: [['Rank', 'Faculty Name', 'Department', 'Evaluations', 'Rating (/5.00)', 'Qualitative Band']],
    body: facultyTableData,
    margin: { left: 14, right: 14 },
    theme: 'striped',
    headStyles: {
      fillColor: [30, 58, 138],
      textColor: [255, 255, 255],
      fontSize: 7.5,
      fontStyle: 'bold'
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [30, 41, 59]
    },
    columnStyles: {
      0: { cellWidth: 12, halign: 'center', fontStyle: 'bold' },
      1: { cellWidth: 'auto', fontStyle: 'bold' },
      2: { cellWidth: 38 },
      3: { cellWidth: 20, halign: 'center' },
      4: { cellWidth: 24, halign: 'right', fontStyle: 'bold' },
      5: { cellWidth: 35, halign: 'center' }
    },
    didDrawPage: (data) => {
      // Add standard footer to each page
      const pageCount = (doc as any).internal.getNumberOfPages();
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(148, 163, 184);
      doc.text(
        `St. Alexius College • TPES Administrative Summary • Page ${data.pageNumber} of ${pageCount}`,
        pageWidth / 2,
        pageHeight - 8,
        { align: 'center' }
      );

      // Bottom Bar
      doc.setFillColor(30, 58, 138);
      doc.rect(0, pageHeight - 3, pageWidth, 3, 'F');
    }
  });

  // --- SIGNATORY & ENDORSEMENT SECTION ---
  const finalY = (doc as any).lastAutoTable ? (doc as any).lastAutoTable.finalY + 12 : pageHeight - 45;
  
  // If not enough room on page, add page
  let signY = finalY;
  if (signY > pageHeight - 40) {
    doc.addPage();
    renderHeader((doc as any).internal.getNumberOfPages());
    signY = 45;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(30, 58, 138);
  doc.text('ADMINISTRATIVE VERIFICATION & ENDORSEMENT', 14, signY);

  doc.setDrawColor(226, 232, 240);
  doc.line(14, signY + 2, pageWidth - 14, signY + 2);

  const colWidth = (pageWidth - 28) / 3;
  const sigPositions = [
    { title: 'Prepared by:', name: generatedBy, role: 'TPES Administrator' },
    { title: 'Verified by:', name: 'Guidance & Testing Center', role: 'Head of Guidance Services' },
    { title: 'Approved by:', name: 'Office of Academic Affairs', role: 'Vice President for Academic Affairs' }
  ];

  sigPositions.forEach((sig, i) => {
    const sigX = 14 + (i * colWidth);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(sig.title, sigX, signY + 8);

    doc.setDrawColor(148, 163, 184);
    doc.setLineWidth(0.3);
    doc.line(sigX, signY + 20, sigX + colWidth - 8, signY + 20);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(15, 23, 42);
    doc.text(sig.name, sigX, signY + 24);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    doc.setTextColor(100, 116, 139);
    doc.text(sig.role, sigX, signY + 27.5);
  });

  const filename = `SAC_TPES_Summary_Report_${selectedDepartment.replace(/[^a-zA-Z0-9]/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}

/**
 * Generates and downloads an Individual Faculty Performance Summary PDF
 */
export function exportIndividualTeacherPDF(
  teacher: TeacherPerformanceData,
  criteriaList: EvaluationCriterion[],
  metadata?: {
    academicYear?: string;
    semester?: string;
    generatedBy?: string;
  }
): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const descriptor = getPerformanceDescriptor(teacher.averageScore);

  // Top Banner
  doc.setFillColor(30, 58, 138); // Navy
  doc.rect(0, 0, pageWidth, 6, 'F');
  doc.setFillColor(212, 175, 55); // Gold
  doc.rect(0, 6, pageWidth, 1.5, 'F');

  // Letterhead
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(30, 58, 138);
  doc.text('ST. ALEXIUS COLLEGE', pageWidth / 2, 16, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('City of Koronadal, South Cotabato, Philippines', pageWidth / 2, 20.5, { align: 'center' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(15, 23, 42);
  doc.text('INDIVIDUAL FACULTY PERFORMANCE EVALUATION DOSSIER', pageWidth / 2, 26, { align: 'center' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(212, 175, 55);
  doc.text('OFFICIAL ADMINISTRATIVE RECORD', pageWidth / 2, 30.5, { align: 'center' });

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, 33, pageWidth - 14, 33);

  // Teacher Profile Card
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 36, pageWidth - 28, 26, 2, 2, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 36, pageWidth - 28, 26, 2, 2, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text('Faculty Name:', 18, 42);
  doc.text('Department / College:', 18, 48);
  doc.text('Email Address:', 18, 54);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(30, 58, 138);
  doc.text(teacher.name, 52, 42);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text(teacher.department, 52, 48);
  doc.text(teacher.email || 'N/A', 52, 54);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text('Academic Term:', pageWidth / 2 + 10, 42);
  doc.text('Student Evaluations:', pageWidth / 2 + 10, 48);
  doc.text('Evaluation Date:', pageWidth / 2 + 10, 54);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(15, 23, 42);
  doc.text(`${metadata?.academicYear || '2025-2026'} • ${metadata?.semester || '1st Semester'}`, pageWidth / 2 + 42, 42);
  doc.text(`${teacher.evaluationCount} Submitted Evaluations`, pageWidth / 2 + 42, 48);
  doc.text(new Date().toLocaleDateString(), pageWidth / 2 + 42, 54);

  // Overall Score Highlight Box
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(14, 65, pageWidth - 28, 22, 2, 2, 'F');
  doc.setDrawColor(191, 219, 254);
  doc.roundedRect(14, 65, pageWidth - 28, 22, 2, 2, 'S');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(30, 58, 138);
  doc.text('OVERALL COMPOSITE EVALUATION SCORE', 20, 72);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(30, 58, 138);
  doc.text(`${teacher.averageScore > 0 ? teacher.averageScore.toFixed(2) : '0.00'}`, 20, 81);
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('/ 5.00 Maximum Rating', 46, 81);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text(`Rating: ${descriptor.label} (${descriptor.code})`, pageWidth - 20, 76, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text(`Official classification per SAC Faculty Evaluation Guidelines`, pageWidth - 20, 81, { align: 'right' });

  // Detailed Criteria Breakdown Table
  const tableData = criteriaList.map((crit, idx) => {
    const score = teacher.criteriaScores?.[crit.id];
    const scoreText = score !== undefined ? score.toFixed(2) : 'N/A';
    const scoreDesc = score !== undefined ? getPerformanceDescriptor(score).label : 'No Data';

    return [
      `${idx + 1}`,
      crit.label,
      crit.description || 'Evaluation dimension criteria',
      `${scoreText} / 5.00`,
      scoreDesc
    ];
  });

  autoTable(doc, {
    startY: 92,
    head: [['#', 'Performance Criteria', 'Description', 'Score', 'Rating Band']],
    body: tableData,
    margin: { left: 14, right: 14 },
    theme: 'grid',
    headStyles: {
      fillColor: [30, 58, 138],
      textColor: [255, 255, 255],
      fontSize: 7.5,
      fontStyle: 'bold'
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [30, 41, 59]
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 42, fontStyle: 'bold' },
      2: { cellWidth: 'auto' },
      3: { cellWidth: 26, halign: 'center', fontStyle: 'bold' },
      4: { cellWidth: 32, halign: 'center' }
    }
  });

  // Signatory Block
  const finalY = (doc as any).lastAutoTable ? (doc as any).lastAutoTable.finalY + 15 : 220;
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(30, 58, 138);
  doc.text('ACKNOWLEDGEMENT & ADMINISTRATIVE NOTATION', 14, finalY);
  doc.setDrawColor(226, 232, 240);
  doc.line(14, finalY + 2, pageWidth - 14, finalY + 2);

  const colWidth = (pageWidth - 28) / 3;
  const signatures = [
    { title: 'Evaluated Faculty Member:', name: teacher.name, role: 'Signature over Printed Name' },
    { title: 'Noted by Department Chair / Dean:', name: `${teacher.department} Dean`, role: 'Signature over Printed Name' },
    { title: 'Certified by VP Academic Affairs:', name: 'Office of Academic Affairs', role: 'Official Seal & Signature' }
  ];

  signatures.forEach((sig, i) => {
    const x = 14 + (i * colWidth);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(sig.title, x, finalY + 8);

    doc.setDrawColor(148, 163, 184);
    doc.setLineWidth(0.3);
    doc.line(x, finalY + 22, x + colWidth - 8, finalY + 22);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(15, 23, 42);
    doc.text(sig.name, x, finalY + 26);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    doc.setTextColor(100, 116, 139);
    doc.text(sig.role, x, finalY + 29.5);
  });

  // Page Footer
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text(
    `St. Alexius College • Faculty Performance Dossier • Confidential Document`,
    pageWidth / 2,
    pageHeight - 8,
    { align: 'center' }
  );

  doc.setFillColor(30, 58, 138);
  doc.rect(0, pageHeight - 3, pageWidth, 3, 'F');

  const filename = `SAC_Faculty_Dossier_${teacher.name.replace(/[^a-zA-Z0-9]/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
